export { DrawerPanel, type DrawerPanelProps } from "./drawer-panel";
// Re-export the atomic parts so a full drawer can be assembled from one entry.
export {
  Drawer,
  type DrawerProps,
  DrawerBody,
  type DrawerBodyProps,
  DrawerClose,
  type DrawerCloseProps,
  DrawerContent,
  type DrawerContentProps,
  DrawerDescription,
  type DrawerDescriptionProps,
  DrawerFooter,
  type DrawerFooterProps,
  DrawerHeader,
  DrawerHeaderContent,
  type DrawerHeaderContentProps,
  type DrawerHeaderProps,
  DrawerProvider,
  type DrawerProviderProps,
  DrawerSwipeArea,
  type DrawerSwipeAreaProps,
  DrawerTitle,
  type DrawerTitleProps,
  DrawerTrigger,
  type DrawerTriggerProps,
} from "../../ui/drawer";
