export * from "./navigation-menu-panel";
// Re-export the atomic navigation menu parts so a full menu can be assembled from one entry.
export {
  NavigationMenu,
  type NavigationMenuProps,
  NavigationMenuArrow,
  type NavigationMenuArrowProps,
  NavigationMenuContent,
  type NavigationMenuContentProps,
  NavigationMenuContentList,
  type NavigationMenuContentListProps,
  NavigationMenuIcon,
  type NavigationMenuIconProps,
  NavigationMenuItem,
  type NavigationMenuItemProps,
  NavigationMenuLink,
  type NavigationMenuLinkProps,
  NavigationMenuLinkDescription,
  type NavigationMenuLinkDescriptionProps,
  NavigationMenuLinkTitle,
  type NavigationMenuLinkTitleProps,
  NavigationMenuList,
  type NavigationMenuListProps,
  NavigationMenuTrigger,
  type NavigationMenuTriggerProps,
  NavigationMenuTriggerLabel,
  type NavigationMenuTriggerLabelProps,
  NavigationMenuViewport,
  type NavigationMenuViewportProps,
} from "../../ui/navigation-menu";
